# Reference: https://www.youtube.com/watch?v=0pYN6Z-t1-s
name: gh-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: MKDocs github pages automatic deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: MKDocs github deploy
        run: |
          poetry shell
          git pull
          mkdocs gh-deploy
